<?php

namespace App\Filament\Resources\CommentResource\Pages;

use App\Filament\Resources\CommentResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateComment extends CreateRecord
{
    protected static string $resource = CommentResource::class;

    protected ?bool $hasDatabaseTransactions = true;

    protected function handleRecordCreation(array $data): Model
    {

        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
