name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - '**.neon'
      - '.github/workflows/phpstan.yml'
  workflow_dispatch:


jobs:
  phpstan:
    name: phpstan (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3]
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          working-directory: "demo"

      - name: Run PHPStan
        working-directory: "demo"
        run: ./vendor/bin/phpstan analyse --error-format=github
